# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/  
# получение датчиков
GET {{baseUrl}}api/v1/sensor-list/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/api/v1/sensor-list/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/api/v1/sensor-list/7/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/api/v1/add-measurement/
Content-Type: application/json

{
  "sensor": 7,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/api/v1/sensor-list/7/
Content-Type: application/json

###

#Get detailed information about the sensor
GET {{baseUrl}}/api/v1/sensor-brief-info/
Content-Type: application/json
